version: "2"
services:
  web:
    image: nginx:latest
    ports:
    - "127.0.0.1:80:80"
    links:
    - php:php
    volumes:
    - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    volumes_from:
    - app_data

  php:
    image: customphp7.1:latest
    expose:
    - "9001"
    links:
    - db:db
    volumes_from:
    - app_data
    environment:
      PHP_XDEBUG_ENABLED: 1 # Set 1 to enable.
      XDEBUG_CONFIG: remote_host=host.docker.internal
  db:
    image: mariadb:10.3
    ports:
    - "127.0.0.1:3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=wordpress
    - MYSQL_USER=wordpress
    - MYSQL_PASSWORD=wordpress
    - MYSQL_DATABASE=wordpress
    volumes_from:
    - db_data
  app_data:
    image: busybox
    volumes:
    - ./../../.:/var/www/html
  db_data:
    image: busybox
    volumes:
    - ./data/db:/var/lib/mysql
    - ./dumps:/docker-entrypoint-initdb.d
